### ISSUE TITLE
Wrong usage of createEffect

### ISSUE THREAD

**Issue by TheComputerM** [TheComputerM/mystic-ui#2]
Dunno why I always thought that cleanup in createEffect was the same as react, as a result components use createEffect incorrectly, will fix as soon as Solid Hack is over.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the createEffect in AnimatedBeam component to properly handle cleanup of the ResizeObserver.

You can review changes in this commit: https://github.com/lattaai13/TheComputerM-mystic-ui-2/commit/b7d5932d4c085eb4a7d381d2d5146a82ce194de4.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
